
# For development use this image
FROM kozhin/rails-server:latest

ENV RAILS_ENV development
ENV NODE_ENV development
ENV DESTINATION_EMAIL tyler@example.com
ENV GOOGLE_MAPS_API AIzaSyCRXbrstYgvIZEWxkSBFoCGeHQpOnNQFHs

# Install necessary packages
RUN apt-get update && apt-get install libpq-dev -y && apt-get clean all

# Set working folder
WORKDIR /app

# Copy gemfile
COPY Gemfile .
COPY Gemfile.lock .

# Install required gems with Bundler
RUN bash -c "source ~/.bash_profile && bundle install"

# We don't expose these ports as we use docker-compose
#EXPOSE 3000 3035

# Application entrypoint
ENTRYPOINT bash -c "source ~/.bash_profile && rails server"
